# SPDX-FileCopyrightText: 2025 Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0

apiVersion: v1
description: A Helm chart for Traefik extra objects.
name: traefik-extra-objects
version: 4.1.4
appVersion: "1.0.0"
