# SPDX-FileCopyrightText: 2025 Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "iam.serviceAccountName" . }}
  namespace: {{ default  .Release.Namespace .Values.global.namespace }}
automountServiceAccountToken: true
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: datamodel-tenancy-installer-role
  namespace: {{ default  .Release.Namespace .Values.global.namespace }}
rules:
- apiGroups: ["apiextensions.k8s.io"]
  resources: ["customresourcedefinitions"]
  verbs: ["get","list","create","update","patch", "delete"]
- apiGroups: ["nexus.com"]
  resources: ["datamodels"]
  verbs: ["get","list","create","update","patch", "delete"]
- apiGroups: ["rbac.authorization.k8s.io"]
  resources: ["clusterroles"]
  verbs: ["get","bind","escalate","create","delete", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: datamodel-tenancy-installer
  namespace: {{ default  .Release.Namespace .Values.global.namespace }}
subjects:
- kind: ServiceAccount
  name: {{ include "iam.serviceAccountName" . }}
  namespace: {{ default  .Release.Namespace .Values.global.namespace }}
roleRef:
  kind: ClusterRole
  name: datamodel-tenancy-installer-role
  apiGroup: rbac.authorization.k8s.io
