# SPDX-FileCopyrightText: 2025 Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0
---

apiVersion: v1
version: 0.1.1
appVersion: 0.1.0
description: Kubernetes Metrics Server
name: k8s-metrics-server
