# SPDX-FileCopyrightText: 2025 Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0

apiVersion: v1
version: 1.0.0
appVersion: 0.1.0
description: AWS load balancer TargetGroupBinding CRDs
name: aws-lb-tgb
